### ISSUE TITLE
Issue with Local Deployment (Ignore - I am the issue. It is me.)

### ISSUE THREAD

**Issue by soccerwithag** [gustavz/DataChad#4]
Running with .env set locally, with python 3.10.9. Requirements installed. Not sure what the issue is. I'm probably just doing something stupid.

streamlit run app.py [ARGUMENTS]
2023-05-26 15:38:22.241 Session state does not function when running a script without `streamlit run`
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/home/.pyenv/versions/DataChad/lib/python3.10/site-packages/humbug/report.py", line 540, in _hook
    self.error_report(error=exception_instance, tags=tags, publish=publish)
  File "/Users/home/.pyenv/versions/DataChad/lib/python3.10/site-packages/humbug/report.py", line 274, in error_report
    traceback.format_exception(
TypeError: format_exception() got an unexpected keyword argument 'etype'

Original exception was:
Traceback (most recent call last):
  File "/Users/home/.pyenv/versions/DataChad/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 376, in __getitem__
    return self._getitem(widget_id, key)
  File "/Users/home/.pyenv/versions/DataChad/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 421, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/home/pytorch-test/DataChad/app.py", line 205, in <module>
    authentication_form()
  File "/Users/home/pytorch-test/DataChad/app.py", line 92, in authentication_form
    f"{st.session_state['mode']} API Key",
  File "/Users/home/.pyenv/versions/DataChad/lib/python3.10/site-packages/streamlit/runtime/state/session_state_proxy.py", line 90, in __getitem__
    return get_session_state()[key]
  File "/Users/home/.pyenv/versions/DataChad/lib/python3.10/site-packages/streamlit/runtime/state/safe_session_state.py", line 113, in __getitem__
    return self._state[key]
  File "/Users/home/.pyenv/versions/DataChad/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 378, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "mode". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'

**Comment by soccerwithag** [comment]
I was stupid. Wasn't running it with streamlit... (streamlit run.py instead of python run.py)
