### ISSUE TITLE
hkunlp/instructor-xl Integrations Error

### ISSUE THREAD

**Issue by puzzle007** [gustavz/DataChad#6]
Solved

**Comment by puzzle007** [comment]
can you please take a look into my code . I am getting following error:
Exception in thread ScriptRunner.scriptThread:
Traceback (most recent call last):
  File "C:\Users\shati\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\shati\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 311, in _run_script_thread
    widget_states = self._session_state.get_widget_states()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 90, in get_widget_states
    return self._state.get_widget_states()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 555, in get_widget_states
    return self._new_widget_state.as_widget_states()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 225, in as_widget_states
    states = [
             ^
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 228, in <listcomp>
    if self.get_serialized(widget_id)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 210, in get_serialized
    serialized = metadata.serializer(item.value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\streamlit\elements\selectbox.py", line 58, in serialize
    return index_(self.options, v)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\streamlit\util.py", line 157, in index_
    raise ValueError("{} is not in iterable".format(str(x)))
ValueError: gpt-4 is not in iterable
2023-07-01 08:38:10.728 Uncaught app exception
Traceback (most recent call last):
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Git_Proj\AREA-V2\app.py", line 254, in <module>
    output = generate_response(user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Git_Proj\AREA-V2\area\chain.py", line 72, in generate_response
    response = st.session_state["chain"](
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\langchain\chains\base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\langchain\chains\conversational_retrieval\base.py", line 106, in _call
    docs = self._get_docs(new_question, inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      ^^^^^^^^^^^^^^
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\langchain\vectorstores\deeplake.py", line 50, in vector_search
    distances = distance_metric_map[distance_metric](query_embedding, data_vectors)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Git_Proj\AREA\.venv\Lib\site-packages\langchain\vectorstores\deeplake.py", line 22, in <lambda>
    "cos": lambda a, b: np.dot(a, b.T)
                        ^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 180, in dot
ValueError: shapes (768,) and (1536,4) not aligned: 768 (dim 0) != 1536 (dim 0)

**Comment by puzzle007** [comment]
Hi @gustavz 
Can you take a look
